### ISSUE TITLE
Week 1 link not working

### ISSUE THREAD

**Issue by dmbartles** [susanBuck/dwa15-fall2017#1]
Susan,

The week one link doesn't seem to be working [http://dwa15.com/week/1](url)
I get the error message below.

Thanks, Matt

![whoops](https://user-images.githubusercontent.com/31462416/29900643-23d55c7c-8dc1-11e7-83e1-b222b96db68c.JPG)

**Comment by oarangel** [comment]
Hello,

I have the same issue

Thanks,

Oscar

**Comment by susanBuck** [comment]
Resolving this now. Will post when done!

**Comment by dmbartles** [comment]
It works! Thanks, Susan.

**Comment by susanBuck** [comment]
I believe the problem was happening to students who did not have a name/location filled out in their Github accounts. It was throwing an error on the course server because it was not expecting those values to be null. Never came up in my own tests because I did have those fields filled in.

I've fixed it so it does not fail when those values are blanked.

Thanks for the heads up Oscar + Matt.
