### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#102]
I'm getting an error that there is no more space on my macbook air 64gb. What should I do? Is there a way I can move the MAMP folder to an external hard drive 1TB to work with it. Please let me know.

**Comment by peggyo** [comment]
Do you have other files that you can move to the external drive - documents, images, etc., in order to free up enough space?  Perhaps back up and remove as much of our past work as you can?

The MAMP documentation says that MAMP must be installed on a system drive, so my first inclination to install MAMP to the external drive won't work unless there is some way to 'trick' it as a savvy Mac user - which I am not.
[https://documentation-3.mamp.info/en/documentation/mamp/](url)  (Scroll down to FAQ, or search for external.)
I found a youtube video about referencing an external drive for the htdocs folder - but it is very old, I wouldn't count on it. [https://www.youtube.com/watch?v=ATuntvuZaf8](url)

I did see some posts in my search related to portable websites with MAMP, but I am on Windows and cannot test any of the ideas - and the posts were fairly old. Another thought, though painful, would be to keep your source for foobooks and p3 in backups on the ext. drive, having only one of them copied to your MAMP server at a time - but that would be painful, too. I hope you can clear enough from other areas without having to do that.

**Comment by samanthi22** [comment]
Thanks. I will try.

**Comment by gvardany** [comment]
How much is your MAMP folder? You might as well consider cleaning up the logs, or configuring it differently, if you are really so short in space. The logs keep growing and should keep an eye on it, once I had a server log that reached 87GB being unnoticed.

**Comment by rrtx2000** [comment]
I agree with Peggyo. Unless there's something unusual like gvardany talks about where you have a extremely large server log, I'd look at cleaning up some other files first. Videos can be very large so that would be the first place I would look. I can't speak to the size of the MAMP folder but I as a reference I can tell you my XAMPP folder is 613 meg.

**Comment by zeroender** [comment]
At this point in the course the MAMP app I have is just under 1.5 gigs, so that is a fair amount of stuff to remove (as others have pointed out, videos are probably the best things to look at in terms of removing).  You could point mamp to look at a htdocs folder on another drive, but my entire htdocs is about 100mb, so I doubt moving that will do you much good.  A better alternative might be just to redownload and reinstall MAMP onto the other drive.

**Comment by ysrinu** [comment]
@samanthi22 I assume 64GB is the hard drive size. And MAMP/XAMP is a very light weight application.
Do you know what's the free space left if you didn't had MAMP installed?
Installing applications on non-root device is not a good idea. You can however have the (web) application folders on another drive, but it's usually a good idea to have these folder on a drive connected to the motherboard (and not as an external drive). Well, the USB 3.0 is much faster so you might try external drive.
This is only a temporary solution to an inevitable problem. You should get rid of as many apps and files that you won't need to reside on your macbook.
My XAMP folder is about 0.5GB but my harddrive is 0.5TB.

Macbook Air is more for mobility and is usually not recommended as a development work device for students or professionals! May be it's time to buy the latest and greatest Macbook or Macbook Pro :-)
https://www.apple.com/mac/

**Comment by HeinrichTremblay** [comment]
You can change the document root of MAMP and put your project on an external drive.

<img width="535" alt="screenshot 2017-10-25 19 21 01" src="https://user-images.githubusercontent.com/5926155/31996116-cbd049da-b94c-11e7-871d-444e3dc59d10.png">

As for MAMP itself, keep it install locally, it's lightweight. If you don't have enough hard drive space, maybe it's time to do some clean up.

**Comment by gabrielsanna** [comment]
@HeinrichTremblay has the right idea. We've used the default htdocs folder so far in this course, but we can actually use any folder on our computer as the document root, including a folder on an external drive, just by changing it in the MAMP settings (and then deleting the contents of the htdocs folder). However, this probably won't save you that much space unless your projects have a lot of images or media files in them.

Also note that by default, the MAMP installer installs a "MAMP Pro" trial in your Applications folder. You can safely delete this to clear a couple more GB—it won't affect your regular MAMP.

**Comment by asmatmuradi** [comment]
I agree with the comments above that MAMP is a very lightweight application. I just checked mine and it was in KBs. So, you may just delete some other files that you don't need on your Mac. Good Luck.

**Comment by mfs780** [comment]
I agree with the above posts how you just need to remove unwanted applications or files from your computer. Try to use cloud storage for your documents.

Here are some of the utilities you can use that were mentioned on an Apple support forum:

https://www.omnigroup.com/more (OmniDiskSweeper)
 
http://grandperspectiv.sourceforge.net (Grand Perspective)
 
http://www.derlien.com/downloads/ (Disk Inventory X)
