### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#107]
When I add this line: $request->validate([
			'people' => 'required|numeric',
			'tab' => 'required|numeric'
			]);

to my controller named create. I get a too many redirects loop. My form uses GET. My routes are Route::get('/form/create', 'WelcomeController@create');
Route::post('/form', 'WelcomeController@store');

I put the validate before the code to compute the bill and display it using return view.

What should I do? What am I doing wrong?

**Comment by dianakleban** [comment]
If you are using GET, you should not be using POST in the route: 
Route::**post**('/form', 'WelcomeController@store');

If you are using POST to process, then you need to put validate code in the **store** function, not **create.**

**Comment by susanBuck** [comment]
Tips to improve this post:
+ [Use Markdown formatting when sharing code-like content in your posts](https://github.com/susanBuck/dwa15-fall2017/issues/22)
+ [Share your repository URL](https://github.com/susanBuck/dwa15-fall2017/issues/96)

**Comment by ysrinu** [comment]
It's okay to have both POST and GET routes setup.
The problem could be that the controller function might be using view that is cross referencing (switch between post and get endless) or self call (same route but endlessly)

**Comment by ysrinu** [comment]
@samanthi22 @susanBuck 
Now, I am getting the 'localhost redirected you too many errors' too :-(
I think this is happening because the base url 

http://p3.srinivasyelamanchili.me/

My routes are:
```
Route::get('/', 'CostController');
Route::get('/cost', 'CostController@index');
```
The form action in index.blade.php is:
`<form action="/cost" method="GET">`

If you click on 'Calculate' link it should take to http://p3.srinivasyelamanchili.me/cost
but it doesn't because of the validation rule (looping?) in CostController.php

```
public function index(Request $request)
    {
        # Validate the request data
    $this->validate($request, [
        'custName' => 'required|alpha',
    ]);
```

**Comment by gabrielsanna** [comment]
Great troubleshooting! I'll try and reproduce when I get a chance.

**Comment by susanBuck** [comment]
I want to rehash some of the points @ysrinu touched on above for the sake of clarity and to make sure we're all on the same page:

We can inadvertently create a redirect loop if we have a feature with the following ingredients:
1. a form submitted with GET
2. a single GET route to both display the form and the results of the form submission
3. validation

For example, imagine the Foobooks *Search* feature had validation. It doesn't, but if it did, the setup would look like this:

Single route to handle both displaying the form and the results:
```php
Route::get('/search', 'BookController@search');
```

The corresponding method:
```php
public function search(Request $request)
{
    # Code to validate request

    # Code to do the search

    # Code to return the view (with results if there are any)
}
```

And of course the view with a form:
```php
<form method='GET' action='/search'>
    <input type='text' name='searchTerm'>
    <input type='submit'>
</form>
```

Let's now outline the problem with this scenario.

+ I visit `/search`
+ The route `/search` is triggered via GET, invoking `BookController@search`
+ The first thing the search method does is try to validate the Request, with a rule stating that the searchTerm input is required.
+ Because I'm just loading this page there's no way I could have filled out that form field, and so the validation fails and by default, redirects us back to `/search`.

Then the process begins all over again and we are stuck in an endless loop of redirects.

## How to avoid this problem

### Option 1)
Make it so the validation method is only invoked if the form was actually submitted. One way we could do this is check the request for the data we're validating for:

```php
if ($request->has('searchTerm')) {
            $this->validate($request, [
                'searchTerm' => 'alpha'
            ]);
}
```

### Option 2)
Use two separate routes - one to show the form, one to check the results of the form. This is how the *Trivia* feature is built. 

Even with two routes, you can still have the "single page" effect if that's what you're aiming for - this is how the *Add a book* feature is built.

**Comment by ysrinu** [comment]
@susanBuck Option 1 works in the foobooks case because no processing needs to happen if search term is empty. However, let's assume that searchterm is one of the required fields to be validated too (from the $request). In that case it will go into indefinite loop.

What does 'submission' really mean? In a form when we hit 'submit' and there's action called (method GET or POST) I understand it's a "submission".
If we enter url with query string parameters in the browser address bar (and hit Enter) is that a "submission" event too? In that case every redirect url with query string parameters strung alone is a submission.
Is there a $request or laravel session environment variable that would identify if a form was submitted by user using the form submit on the UI instead of using url with query string params?

**Comment by rrtx2000** [comment]
I also had a problem with too many redirects after I put in the validation. I could take the validation out and it wouldn't redirect but as soon as I put the validation back in it would have the same issue. All of a sudden it started working so I think it might have been a caching issue and I couldn't get it to fail again.
