### ISSUE TITLE
Dynamically add a CSS-style

### ISSUE THREAD

**Issue by nekoCC01** [susanBuck/dwa15-fall2017#118]
I would like to **dynamically add a CSS-style (background-image)** into my view, with the Controller providing the img-url.
An easy way that works would be to just define an **inline-style** and add the variable into it:

`<div id="author_img" style="background-image: url('{{$img}}');"></div>`

([link to the Github-file](https://github.com/nekoCC01/DWA-Project03/blob/master/resources/views/quote/pretend.blade.php))

But that would collide with the separation of concerns and the requirement to avoid inline styles.
Did anyone have a similar issue and solved it in another way?

(A slight improvement would be to use an embedded style instead:)
```
@push('head')
    <style>
        #author_img {
            background-image: url('{{$img}}');
        }
    </style>
@endpush
```

**Comment by ALiborio** [comment]
The only thing I can think of is to use PHP to create your CSS file, and therefore be able to setup the variable background image.

This page has some details on how to do that:
https://css-tricks.com/css-variables-with-php/
However, some in the comments are saying not to do this kind of thing because of the performance implications. I have not tried this myself, so your results may vary. 

If that doesn't work or seems like too much work, I think the embedded style is probably the best solution.

**Comment by nekoCC01** [comment]
@ALiborio Thanks for the comment!
I guess, I´ll stick to the embedded style then.

**Comment by susanBuck** [comment]
Typically if I want some CSS to be influenced by PHP I would create a class (or id) that sets the appropriate style, then apply that class name to the element with PHP.

But in this case, it sounds like each author div has it's own unique background? That'd require a lot of classes, which wouldn't be efficient or dynamic.

So in that case, I agree embedding the style is the best option.

I think the only thing I'd question is why display the author image as a background image, rather than just an image element? The former (typically) is more accessible than the latter.

**Comment by nekoCC01** [comment]
@susanBuck Thanks for the comment!
I used img-elements in other places, but this time I needed some additional CSS-styling, to make the image fit into a div, like so:
```
div#author_img {
    z-index: -1;
    position: absolute;
    top: 280px;
    left: 400px;
    width: 220px;
    height: 260px;
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
}
```
This is easier to accomplish with a background-image than with an img-element, I guess.
