### ISSUE TITLE
Using True, False, 0 or 1 In a Column

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#134]
## Scenario
You do not want to permanently delete a row and  you have a column named delete or a disable.

## Question
For column type would it matter if you use ENUM('true', 'false') or TINYINT('delete') and use 0 and 1?

**Comment by ruthnphillips** [comment]
I think it will be a personal preference. I would use `boolean('delete')`

**Comment by dukesnuz** [comment]
@ruthnphillips Did not even think of boolean().  Was wondering if either of above is more compatible  with php and efficiency.

**Comment by dukesnuz** [comment]
Think I just found my [answer.](https://stackoverflow.com/questions/2989281/appropriate-data-field-type-for-true-false-value).

**Comment by luke777gu** [comment]
yes, boolean should be used in this case.

**Comment by gregorycoleman** [comment]
Laravel Eloquent has soft deleting.

Instead of actually removing records from your database, Eloquent can also "soft delete" models. When models are soft deleted, they are not actually removed from your database. You can retrieve them, recover them or permanently delete them.

<https://laravel.com/docs/5.5/eloquent#soft-deleting>

**Comment by ysrinu** [comment]
TINYINT can take values in the range -128 to 127 and 1 Storage Bytes
MySQL BOOL or BOOLEAN is equivalent to TINYINT(1)

For yourcase, you can use either TINYINT(1) or BOOL or BOOLEAN, but avoid TINYINT greater than TINYINT(1). This will make it impossible (or make fail) inserting values that are not 0 or 1.

https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html

Regarding deletes, most database can do soft-delete. However, in a real data warehousing / transaction env, the records can simply be marked as 'deleted' (with a column value set) from application perspective (not from database engine perspective). This is necessary for auditing purpose.
The 'deleted' records can then be migrated to an archive (db table, flat file or tape) or not, and then permanently deleted. It's all depends on regulatory and compliance requirements and data the company has to adhere to

**Comment by dukesnuz** [comment]
I wonder if any of the above is more efficient and has better performance when working with PHP and Laravel.

**Comment by susanjiang03** [comment]
Tinyint is fine if you have  no more than two values, null, 1 or 0, or ture or false. but  I would like to  use enum type, so later, maybe you want to add some other status or states , for e.g. a record could have different status like "created", "modified", "finished","deleted","active","inactive", etc.

**Comment by susanBuck** [comment]
Weighing in and echo'ing @gregorycoleman's note: I'd take a look at [Laravel's soft delete feature](https://laravel.com/docs/5.5/eloquent#soft-deleting).

Soft-deletion uses a field called `deleted_at` (similar to the `created_at` and `updated_at` fields).
If that field is `null`, we can assume the record has not been deleted.
If that field contains a timestamp, it means the record has been soft deleted and the timestamp represents when.

This is more ideal than simply recording True/False for deletion because a) it tells us when the record was deleted and b) we can take advantage of Laravel and Eloquent's<sup>1</sup> built in functionality for managing deletions. 

If you did not want to use Laravel's soft-deletion functionality and instead manage the deletion field yourself, then I concur with the above posts that `$table->boolean('delete')` (which will create a `tinyint(1)`) is the way to go.

*<sup>1</sup> Eloquent is a topic covered in this week's material (11)</small>*

**Comment by dukesnuz** [comment]
@ruthnphillips @luke777gu @gregorycoleman @ysrinu @susanjiang03 @susanBuck 
Thx
I am going with ```$table->softDeletes();``` for soft deleting and ```$table->boolean('active')->default(0);``` for column that was called disable and is now called active which is defaulting to 0.
