### ISSUE TITLE
Create migration script from tables

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#135]
Hi, we have seen in the lecture notes how to create tables using SQL syntax from command line or visually using tools like phpMyAdmin.
Wouldn't it be nice if we could generate laravel migration script from an existing table?
I found a very 'close' solution to this. 'Close' because the solution I found online creates migration script from model and not from actual table.

I downloaded and installed MySQLWorkbench and to this client added a plugin that will export a model table as migration script.

Note that creating script this way is only beneficial if you are creating models first. I wouldn't create model just for the sake of migration script, because the time spent in creating model can be used to update the script manually myself!

https://github.com/beckenrode/mysql-workbench-export-laravel-5-migrations

https://dev.mysql.com/downloads/workbench/

![image](https://user-images.githubusercontent.com/25366909/32578970-44bdbc40-c4ad-11e7-82f4-8838f915b394.png)

![image](https://user-images.githubusercontent.com/25366909/32578986-53e969bc-c4ad-11e7-8e31-17f9a8c39fac.png)

Thanks,
-Sri

**Comment by asmatmuradi** [comment]
@ysrinu Thanks for sharing this great tip. For a person like me, with a little database experience, it is much easier to create tables using the workbench and export them. I was not sure about the table constraints using Laravel methods.

**Comment by mfs780** [comment]
@ysrinu Thanks for the tip!

**Comment by nekoCC01** [comment]
@ysrinu Thanks for sharing! This is good to know!

**Comment by arow510** [comment]
Thanks for sharing. Working with databases is somewhat of a new topic for me. It's been almost 10 yrs since, I've done a query or created a table using SQL.  I found that using the copy option in phpmyadmin to be pretty useful in this process as well. Once you select what you want to copy hit the drop down for the with selected option and it will give the option to copy. 

![image](https://user-images.githubusercontent.com/31460880/32693464-14dfce98-c6e0-11e7-8078-49ca8c962ea8.png)
