### ISSUE TITLE
Directory Structure when Using Subdomains

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#137]
### Scenario
A site consists of the following:
Second level domain ie domain.com
Three sub-domains ie admin.domain.com, p1.domain.com and p2.domain.com
Each domain needs access to the same database. 
_______
### Questions
If all domains are using Laravel, then would the second level domain and all the sub-domains have their own  separate Laravel  project folders as we have done in class?  ie p1, p2, p3(given they are all using Laravel).  What about domain.com's Laravel files? Would they be loaded into the html folder and not in their own folder as p1, p2 p3 would be?

In production  html folder structure would be:   Laravel's files for domain.com, p1, p2, p3?

Then in each Laravel project's  env file would the database connection  would simply be ```DB_DATABASE=database```. ? 

Wondering if this is the best way to structure a site or if other directory structures would be more suitable. Just seems like there is a lot of redundancy this way. It does seem to break the site down into easily workable separate sections for future work and upgrades. 

Any ```<input type='text' name='input'>``` is appreciated.

**Comment by gabrielsanna** [comment]
For my own sites, I always have the second level domain in its own folder, as if it were a subdomain. Another way to think about it is, each VirtualHost in Apache should have its own folder, instead of nesting subdomain folders inside higher level domains.

Consider:

If you have a second level domain with a DocumentRoot of `/var/www/html`, and then a subdomain with a DocumentRoot of `/var/www/html/p3`, then you would be able to access p3.domain.com by going to domain.com/p3. This is not desired behavior. The situation is a little different with Laravel because we're using the `public` folder as our document root, but I'd say it's still better to separate domain.com and *.domain.com into separate folders.  So yes, my suggested folder structure would be:

```
/var/www/html/domain.com
/var/www/html/p1.domain.com
/var/www/html/p2.domain.com
/var/www/html/p3.domain.com
```

Note that the directory structure has no impact on accessing databases. MySQL databases are independent of the structure of your web files—no matter where you place these files they will still be able to access the MySQL database. You're actually connecting to them via a network address rather than pointing at the files where the tables are stored (127.0.0.1:3306 or localhost:3306 are interchangeable—this basically just tells the server to connect to itself on port 3306) .

**Comment by gabrielsanna** [comment]
Sure, but I guess now I'd ask how you're structuring your site(s). If you
have multiple addresses pointing to the same database and using the same
styles, does it make sense to have a single Laravel instance and have
separate routes and views for your separate pages? If you want a page to be
accessible from a subdomain, you can use Apache to redirect it to the
appropriate route.

**Comment by dukesnuz** [comment]
@gabrielsanna  Thank you.  Light bulb just went off. Yeh can have one Laravel project and simply have Apache  redirect to correct DocumentRoot and Directory.

**Comment by dukesnuz** [comment]
@gabrielsanna Many Thanks. Light bulb just went off. Yeh can have one Laravel project and simply have Apache redirect each sub-domain to correct directory.

**Comment by dukesnuz** [comment]
#### Update
I am using Apache to redirect each sub-domain.  I am also using Laravel's [Sub-Domain Routing]([url](https://laravel.com/docs/5.5/routing#route-group-sub-domain-routing)) in my routes file to capture a portion of the sub-domain to use in the route controller.
