### ISSUE TITLE
Eloquent, Get or Fail

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#145]
https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/28_Query_examples.md
https://laravel.com/docs/5.5/eloquent

> Not Found Exceptions
> Sometimes you may wish to throw an exception if a model is not found. This is particularly useful in routes or controllers. The findOrFail and firstOrFail methods will retrieve the first result of the query; however, if no result is found, a Illuminate\Database\Eloquent\ModelNotFoundException will be thrown:

Is there a way to fetch multiple rows and if none found then fail? like` getOrFail`?
Or is using `Count` (and custom code to fail if count=0) the only workaround for this?

Thanks,
-Sri

**Comment by susanBuck** [comment]
Not that I'm aware of. Checking the count of the results, or using [isEmpty](https://laravel.com/docs/5.5/collections#method-isempty) are your options.

I think there's no method for that because typically if we're looking for multiple records and the search turns up empty we don't want to throw an Exception but instead display some "no results found" message to the user.

Whereas if we're looking for a single record there's typically an expectation that it *should* exist, and thus an Exception is logical if it's not. Of course this isn't always the case, which is why you can choose to use `first` instead of `firstOrFail`.
