### ISSUE TITLE
MySQL search on varchar datatype is case-insensitive

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#147]
In https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/22_Database_Primer.md#sql
the 'books' table was created with column 'title' as varchar datatype.
MySQL search on varchar datatype is case-insensitive

Therefore, if our 'title' (varchar) column has value 'The Great Gatsby', it will be returned for search on 'the great gatsby'.
The Eloquent query:
`$result = Book::where('title', '=', 'the great gatsby')->get();`
translates into
`select * from `books` where `title` = 'the great gatsby'`

and the below record is returned:
![image](https://user-images.githubusercontent.com/25366909/32819337-beaeb17e-c996-11e7-8a1b-674f725bbc67.png)

datatype varbinary should be used in place of varchar for case-sensitive search
https://dev.mysql.com/doc/refman/5.7/en/case-sensitivity.html
https://dev.mysql.com/doc/refman/5.7/en/binary-varbinary.html

**Comment by susanBuck** [comment]
__Correct, varchar is case insensitive in regards to searching.__

This raises an interesting question: should the book fields be case sensitive? 

There was an example in the query practice from Week 11 that touched on this slightly:

> #6: Find all books by the author Bell Hooks and update the author name to be bell hooks (lowercase).

Is it possible to accomplish this task even though our author field is varchar and thus case insensitive? Yes, it's just slightly inefficient; here's why:

If we have a book where the author is `Bell Hooks` the following query will run an update on that one book:

```php
Book::where('author', '=', 'Bell Hooks')->update(['author' => 'bell hooks'])
```

At that point, we'd have a book where the author is `bell hooks`. 

If we ran the same query again, it would again run an update on the book, even though it would be unnecessary because the author was already `bell hooks`.

This kind of case switching is really just an example, though, so I wouldn't let it dictate that the author field should be varbinary. More often than not, we do want our fields to be case insensitive because we don't want to treat `J.K. Rowling` and `j.k. rowling` as two distinct authors when searching.

Very interesting questions to think about when it comes to db design, thanks for raising this point @ysrinu!

**Comment by ysrinu** [comment]
Thanks @susanBuck . Last night I sent an email explaining how I worked around making the update case-sensitive from eloquent point of view even if MySQL is case-insensitive.
Most databases are case-insensitive for performance reason and instead of using varbinary, they use an additional clause along with 'varchar' to make it case-sensitive (Teradata for example).

Along the example of 'bell hooks' it would be unnecessary update where the author value is already in lower-case, because updating regardless will update the 'updated_at' timestamp and is bad business practice for auditing reasons.

**Comment by susanBuck** [comment]
Hi @ysrinu - Haven't gotten to your email yet, but I was just recording today's videos and sharing solutions to the query practices and noticed something interesting related to this point:

> [...] when updating, ideally we do not want to update where the value already matches the same case as the one we intend to. It would be unnecessary update where the author value is already in lower-case, because updating regardless will update the 'updated_at' timestamp and is bad business practice for auditing reasons.

In my tests, Eloquent will *not* run an update if the value already matches, so there will not be an unnecessary query.

**Comment by susanBuck** [comment]
Update: Turns out the above statement is true *depending* about how you go about your update.

For example, in the following approach the unnecessary update is avoided:

```php
$books = Book::where('author', '=', 'Bell Hooks')->get();
$matches = $books->count();

if ($books->count() > 0) {
# Loop through each book and update them
    foreach ($books as $book) {
        $book->author = 'bell hooks';
        $book->save();
    }
}
```

This results in __1 query__, to select the books, but Eloquent does not run another query to update the book if it determines the author name is already `bell hooks`.

In the following approach, though:
```php
Book::where('author', '=', 'Bell Hooks')->update(['author' => 'bell hooks']);
```
An update is run, even if the author name is already `bell hooks`

However, in this latter approach it's still only __1 query__ because the search/update is rolled into one:
```
update `books` set `author` = 'bell hooks', `updated_at` = '2017-11-15 14:53:26' where `author` = 'Bell Hooks'
```

This does change the `updated_at` field though, which as you pointed out, is not optimal.
---

Lots of intricacies to consider here. Very interesting things to think about.

I typically only use varbinary if the casing is pertinent to the data... for example, let's say I had a `coupons` table with codes that were case sensitive.

Otherwise, it's not worth the compromise of being able to easily do case insensitive searches.

**Comment by ysrinu** [comment]
@susanBuck I have a workaround to make it case sensitive from php point of view. This is possible (even if mysql is case-insensitive) because mysql will always return with the correct case (even if the search is case-insensitive). Once the data is fetched, in php code we can do conditional update. More details in my email from last night :-)

I agree that we shouldn't change database column to varbinary just for our specific use-case. Typically retrieving is done without regards to case and that's how the column datatype should be defined. If update has to be done based on case sensitivity then it should be up to the application logic code to determine which records need to be updated.
