### ISSUE TITLE
Production Domain step does not work

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#15]
I followed all instructions for setting up Production p1 domain and when I type  http://www.p1.ilearndk.me , I am getting redirected all the time to this below. But when I do http://p1.ilearndk.me, it works. If I type: p1.ilearndk.me, it is getting redirected as well. My understanding was that it is supposed to work in all 3 cases?
![image](https://user-images.githubusercontent.com/31451809/30256467-b140eede-9670-11e7-98bd-e424f8a82d94.png)

I am not sure what I am missing. I set up subdomains, changed config and restarted apache. I can see "www" A Record set up as well. Any ideas?
![image](https://user-images.githubusercontent.com/31451809/30256583-7d8da536-9671-11e7-880c-3b34d7280c14.png)

![image](https://user-images.githubusercontent.com/31451809/30256595-90d2da12-9671-11e7-8a65-0df0eb8a5422.png)

**Comment by davida26** [comment]
Hi @dianakleban 

I see this currently working as expected: http://p1.ilearndk.me

The reason you are not seeing this one work: http://www.p1.ilearndk.me is because you are actually asking for a record for "www.p1"vs "www" or "p1" - no need to combine them. 

Also your http://www.ilearndk.me/ - the "www" should be a CNAME record. CNAME records are aliases of an A record. 

Should look like this: 
`CNAME www ilearndk.me.`

**Comment by gregorycoleman** [comment]
Hi @dianakleban
There is nothing wrong with your setup. http://p1.ilearndk.me  is the domain you should be using.  http://www.p1.ilearndk.me is not used in this course. 

Web domain names do not have to start with www, although they often do.
