### ISSUE TITLE
Slight correct/update to foobooks - links to new books created

### ISSUE THREAD

**Issue by zeroender** [susanBuck/dwa15-fall2017#154]
I noticed after updating my foobooks locally that attempting to click any of the links for the newly created books didn't work.  The index.blade.php file has this code to display the new books as hyperlinks:

`<li><a href='/book/{{ kebab_case($book['title']) }}'>{{ $book['title'] }}</a></li>`

I think linking by title was from prior to switching to using the database - changing that line to

`<li><a href='/book/{{ kebab_case($book['id']) }}'>{{ $book['title'] }}</a></li>`

Updates the link with the book's id, which the controller is looking for.

HTH anyone who like me decided to get their foobooks back up to date!

**Comment by susanBuck** [comment]
Thanks @zeroender for the note. You can see this reflected in the [Week 12 commit to foobooks](https://github.com/susanBuck/foobooks/blob/master/resources/views/book/index.blade.php#L30). I think it was part of the misc. clean-up I did after recording, pre-committing changes though - which is why it might not have been obvious.

FYI In your code, you can omit the `kebab_case` helper - that was only necessary to convert titles like `The Great Gatsby` to a URL friendly version, `The-Great-Gatsby`. Because we're using IDs now, it's no longer needed.

**Comment by zeroender** [comment]
Ah understood.  Thanks!
