### ISSUE TITLE
array, loop through original attributes, not relations

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#168]
In https://github.com/susanBuck/dwa15-fall2017/issues/166
I showed how the code
```
dump($result) # Only asset data, No assetrepairs data
dump($result->assetrepairs # runs a query and only displays assetrepairs data
dump($result) # now has both asset and assetrepairs data
```

displays data as
![image](https://user-images.githubusercontent.com/25366909/33235101-8d9bcf10-d1ff-11e7-93b0-8d9c09b7fcaf.png)

Now, in my blade code, I want to loop through the original attributes array and skip the relations (assetrepairs) data
so that the below code works:
```
@foreach($result->toArray() as $key => $value)
    <h2>{{ $key }} : {{ $value }}</h2>
@endforeach
```

Otherwise, when it loops through the 'assetrepairs' as the $key, it fails printing $value (because it's a collection) with error:
```
ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, array given
```
I can rewrite the code as (to avoid error):
```
@foreach($result->toArray() as $key => $value)
    @if (gettype($value)!='array')
	<h2>{{ $key }} : {{ $value }}</h2>
    @endif
@endforeach
```

but I am looking for a way to omit any the relations attribute (in case I want to use collection if any in the original attributes)

**Comment by susanBuck** [comment]
I'm not aware of a more elegant solution for what you're trying to do than what you've come up with `gettype`.

But I question the need to do what you're doing.

There are very few instances in which you want to loop through and display *all* properties of a row. For example, here are the fields you end up printing out:
```
id : 1
created_at : 2017-11-07 19:33:19
updated_at : 2017-11-07 19:33:19
description : bibendum ullamcorper. Duis cursus, diam
owner : Mary
purchase_price : 8.52
purchase_date : 2017-01-27
group_id : 5
serial_number : O4Z 8B7
location_id : 4
warranty_id : 1
notes : Nunc ut
estimated_life_months : 34
out_of_service_id : 3
out_of_service_date : 2018-07-08
vendor_id : 3
assigned_to : Stacey
assigned_date : 2017-12-17
is_computer : 0
tag : DLD48QLXRP
scheduled_retirement_year : 2020
```

Several of these fields probably don't need to be displayed, at least not without some modification (e.g. converting the `created_at` to a more human friendly date format, displaying `is_out_of_service` as a checkbox rather than a 1/0, etc.).

Instead we typically "cherry pick" what fields we want to display, and we often do some modifications to those values before display, e.g. :

```html
<h1>Asset #{{ $result->id }}</h1>
Serial number: {{ $result->serial_number }}

<p>
{{ $result->description }}
</p>

<label> Out of service
<input type='checkbox' @if($result->is_out_of_service) ? 'CHECKED' : ''>
</label>

[etc...]
```

When you do it this way, you don't have to worry about "skipping" over the table relationship portion of the data because you either exclude it, or write the code necessary to properly display it.

But- You know more about your app than I do - there may be a reason you want to simply loop through all properties and print them. If that's the case, then yah, I think your `gettype` solution is the best bet.

**Comment by ysrinu** [comment]
Thanks @susanBuck I agree that some of the fields shouldn't be displayed as it is (id values). That's on my to-do list in the next set of changes; to show an 'equivalent' value or not display at all.

Sometimes I do code where it may not be the best for html output, but that doesn't stop me from trying to find the correct code, because even if it may not make sense in the current case (html) I may have the need for it somewhere else. So here my focus has shifted to 'how can I loop through result set and skip through relation attributes', and not much about 'loop through all fields except relations to display in html'. The former might be needed at different place, different time!

And as you pointed out gettype() might be the best solution for now.

**Comment by susanBuck** [comment]
👍
