### ISSUE TITLE
Advanced DNS Understanding

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#17]
I would like to extend my understanding about the subdomains. When I just created a new domain in namecheap, I had these CNAME and URL Redirect Record settings for "www" and "@". Then I changed them to A Record(s), per class lecture. However, I am not sure I understand the difference between them and how they are used. Should I have left them the way they were OR it does not matter OR I did it correctly by changing to A Records (which I don't know what it means).

![image](https://user-images.githubusercontent.com/31451809/30332492-0113e45e-97a0-11e7-9b9e-4915a7d55b2e.png)

**Comment by gregorycoleman** [comment]
This may be helpful

Please don't set up a CNAME record for a bare domain e.g., yourdomin.tld (@ hostname since it may affect the operation of the domain's MX records and, consequently, the email service. Thus, in most cases you will need to create a CNAME record for WWW (or other subdomain) and URL Redirect for @ that will point to http://www.yourdomain.tld/

From [How can I set up a CNAME record for my domain?](https://www.namecheap.com/support/knowledgebase/article.aspx/9646/10/how-can-i-set-up-a-cname-record-for-my-domain)

**Comment by gabrielsanna** [comment]
An A record is a "primary" record—you need one of these per domain, and it maps directly to an IP address.

A CNAME is a canonical name—it can be thought of as a shortcut to another record (typical an A record). In most cases, server admins want www.website.com to simply forward to website.com. So, "www" is configured as a CNAME for website.com. You CAN make an A record for www.website.com instead, but typical we wouldn't because website.com is already pointing to that IP address.

You can read more about this distinction here: https://support.dnsimple.com/articles/differences-a-cname-records/

How your server actually responds, though, is configured in your web server (Apache, in our case). When a client such as a browser requests a web address (www.website.com), Apache gets the request, compares the address to the list of virtual hosts, and decides what files to serve accordingly. If you have multiple addresses pointing to the same site, you want to be sure you have the ServerAlias set in the virtual host. So for example, in my gabrielsanna.com .conf file, I have the line

`ServerAlias www.gabrielsanna.com`

so that requests for either gabrielsanna.com or www.gabrielsanna.com go to the same place.

Does that make sense? I used to have trouble with the fact that name resolution (using DNS to figure out which IP address we're going to) and the server behavior (what web files are actually being served) are two different steps.

**Comment by susanBuck** [comment]
Reading this reminds me of a correction I should point out: In the lecture video it shows `www` as a `A` record. This works, but the ideal choice for it is `CNAME`, as @gabrielsanna described above.

It is correct in the notes screenshot ([ref](https://camo.githubusercontent.com/b6f23254142e556fda3f50fbc4996599e63238cd/687474703a2f2f6d616b696e672d7468652d696e7465726e65742e73332e616d617a6f6e6177732e636f6d2f76657273696f6e2d636f6e74726f6c2d6e616d6563686561702d646e734032782e706e67))

Sorry for any extra confusion this may have added. And good questions- thanks for the prompt to clarify the difference between `A` and `CNAME`.

**Comment by ysrinu** [comment]
A related observation I made: 
The CNAME record appended period (.) to Value on 'save' no matter I attempt to remove it. I first attempted to remove because I thought I typed it accidentally and therefore caused the domain not to work (it was an unrelated issue and fixed later). I then realized the period is necessary and the namecheap autocorrected when the period was not there.

**Comment by susanBuck** [comment]
I believe @gabrielsanna's note and the referenced article does a good job of explaining the differences between `cname` and `A` records, so I'm going to close out this issue. If you have follow-up questions, @dianakleban , feel free to keep the conversation going.
