### ISSUE TITLE
Find if a column is a foreign key and the foreign table name

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#171]
My migration scripts have foreign key relationships defined
https://laravel.com/docs/5.5/migrations#foreign-key-constraints

In my Asset model, I declared relations to other models (which makes use of foreign keys)
https://laravel.com/docs/5.5/eloquent-relationships

Now, as I am looping through each column returned for an Asset record, I want to check if that column is a foreign key to another column. So let's say I come across 'vendor_id', I need utility that tels me that vendor_id is mapped to Vendor model on 'id' column (`assets.vendor_id = vendors.id`) returns the foreign table name, here 'vendors'.

What I am NOT looking is to check if a model has foreign keys (this is too generic and suitable for other use case). What I am looking is, given a 'column' I want to know if it's foreign key and if so, then from which table (name).

```
@foreach($result->toArray() as $key => $value)
   // check if $key refers to another table column and get that table name
@endforeach
```

Thanks
-Sri

**Comment by susanBuck** [comment]
If you've defined a field in your table to be a foreign key, it is/always will be a foreign key, and it will always be to the same table. This should not be something you have to figure out programmatically. 

It sounds like you're trying to accomplish something similar to what you've described in #168... you're looping through *every* property of an object and trying to do different things with it depending on the characteristics of that property. For example,

+ If it's a regular field, like the serial number, print it.
+ If it's data from a related table, skip it.
+ If it's a foreign key, [insert what you want to happen here]

As I mentioned in #168, I don't think a loop through all the data is the approach here. Instead, pluck out the data you need and write the code appropriate to handle that data.

Loops are good when we have some variable or unknown amount of data, e.g. rows in a table.

But fields in a given row - that is not unknown or variable. To try and handle each field via a loop creates unnecessary work.

**Comment by ysrinu** [comment]
@susanBuck Those are very good points.
Here's my use case. I am printing each row and column from assets table in a grid format.
Now, wherever we have an '*_id' column, I want to embed hyperlink that will show details from the other table it points to.
Ideally I don't even want to check if the column name ends with '_id'.  I would think there would be function in laravel/eloquent to do this check and return appropriate metadata.

Below is my code to embded hyperlink for group_id and location_id column values for assets records
![image](https://user-images.githubusercontent.com/25366909/33287535-fe03b762-d386-11e7-821f-ae4a35535c93.png)

![image](https://user-images.githubusercontent.com/25366909/33287573-187c8344-d387-11e7-8464-82b8a235982e.png)

Clicking on group_id=5 opens new window for groups table record (used dump statement for now)
![image](https://user-images.githubusercontent.com/25366909/33287445-aaca0a1a-d386-11e7-8219-84f35a9540c9.png)
Similarly for group_id=4
![image](https://user-images.githubusercontent.com/25366909/33287616-3ca7b324-d387-11e7-8cc8-e1128910f023.png)

My intention is to remove the if-else code for each key check and remove hardcoding the url for that key.
If I can collapse the entire if-else-endif block into this:
```
if ($key references column in another table)
<td><a href="{{ URL::to('<referenced table name>/'. $value) }}" target="_blank">{{ $value }}</a></td>
```

Thanks,
-Sri

**Comment by SridharSubramaniam** [comment]
@ysrinu 

Couple of suggestions (not solving your core ask, but something relevant to a discussion)

Even if there is a method to find if it is a foreign key, you wouldn't want to use that in a blade template. That would be tightly couple template to the backend. Isn't it?

In general, Displaying columns dynamically isn't advisable because it wouldn't guarantee the order of it and we are leaving the presentation at risk as things can change depends on the array order.

You may want to consider statically adding markup for columns like Susan suggested in a diff thread. 

Also, one suggestion would be to move an "ID" link to another child template and include that template in your loop so you can have consistent markup across the board.

**Comment by ysrinu** [comment]
Sridhar, 'tightly coupling' should not be an issue. When we define models, we define any relations to other models. So if model-to-model relation info is baked into the model and used in queries, why can't we use the same for printing to html output?

There's a reason I am not statically adding markup for each column, because I want to use the same code across all table displays. Consider you want to scale to 50-60 tables, it would take a lot of efforts to write each column html code for table, plus the effort is multiplied so many times when you have to make a similar change across all.

In my case, the order of columns is not a big issue. I can always reorder in the migration script, since the columns fetched will be in the same order.

"ID" link child template is a good idea but doesn't really solve problem here where we have multiple columns. And we have to be open to the possibility that the columns names may not need to end with '_id' and still have additional info in another table. This template is good for reusable but to provide runtime values we still have the same issue as how to do we pass info realtime of the relation metadata.

Let's ignore that we are printing data to a web page. We can have scenarios where we want to loop through a table (model) columns and want to get the column metadata and verify if it's related to another table column.

When models are defined to be related to other models (and inverse relations too), that itself says that the model has metadata for that relationship; so I would fairly think it should be easy to fetch the same metadata.

**Comment by SridharSubramaniam** [comment]
Well, HTML is presentation and Models are backends, behavior(methods) of one can change without informing other.  Data can be shared but would be ideal to avoid methods. 

What you are looking for is a metadata driven UI in which case, one option would be to construct metadata seperately and pass to the the template instead of directly looking at it from data from the template.

`metadata: {
 groupId ="ref",
 id="number"..
 ..
}, 
data: []`

Will follow this thread to see if there is any way to get metadata automatically.  One crude option I could think of is issuing a describe to actual table itself (but that sounds awful even as I type it :-) )

**Comment by ysrinu** [comment]
@SridharSubramaniam you make a very good point of separating the business logic from presentation code. 
I searched online and couldn't get to clean solution yet to my requirement of querying a column for it's metadata. This would look like such a basic and simple need!

**Comment by susanBuck** [comment]
>> There's a reason I am not statically adding markup for each column, because I want to use the same code across all table displays. Consider you want to scale to 50-60 tables, it would take a lot of efforts to write each column html code for table, plus the effort is multiplied so many times when you have to make a similar change across all.

Gotcha. I could see this if all the tables were similar and just needed basic CRUD functionality.

Anything beyond that, though, and I'd caution against a "one size fits all" approach. You'd end up with super DRY code but it'd be so complex that working with it would be a hassle.

(Not to discourage you from exploring. I think it's cool that you're trying/thinking about this stuff. :-)

>> I searched online and couldn't get to clean solution yet to my requirement of querying a column for it's metadata.

What about some of the info described here:
<https://stackoverflow.com/questions/510410/getting-table-metadata-in-mysql> ?

Other notes: 
You may be interested in checking something like this out: 
<https://github.com/InfyOmLabs/laravel-generator>

Even if it's just to look at the source code and see how they're doing things.

Another thing you might be interested in is this: https://laravelcollective.com/docs/5.2/html
It's a package that gives you macros for building HTML forms conveniently. It doesn't completely "universalize" the form building, but it does make things more terse.

I'm going to go ahead and close this thread out because I don't think there's a pending question to be resolved, but feel free to keep the discussion going. Very interesting things to think about!
