### ISSUE TITLE
Foobooks return redirect not working

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#173]
I cannot seem to get the '/book/create' view to redirect to the '/book/' view. It takes the information but it stays on the same page with no noticeable change. Code is below.
<img width="642" alt="screen shot 2017-11-28 at 6 48 26 pm" src="https://user-images.githubusercontent.com/31494476/33350619-c2f5eaa4-d46d-11e7-9b16-033f2dfa7458.png">

Is there anything wrong here, or should I be checking somewhere else perhaps? Maybe my routes are mixed up?

**Comment by susanBuck** [comment]
> it stays on the same page with no noticeable change

Making sure we're on the same page:
You hit the submit button to create a new book, but nothing appears to happen?

Or does the form submit and then... ? 

Also, some follow-up questions to help troubleshoot:
+ Open the database in phpMyAdmin - is the book actually being added or is that failing too?
+ What happens when the form fails validation?
+ What happens if you put a `dump('You are here')` statement right before the return redirect and comment out the return redirect? When run, this should output the message `You are here`. If you see the message, you know your code is getting to that point. If you don't see the message, you know the problem is not in the redirect itself, but somewhere else.

**Comment by susanBuck** [comment]
Ok, the fact that the book is not actually adding is a helpful clue. 

Reiterating my above question, can you describe what happens when you hit the submit button on this form?

Does absolutely nothing happen?

Does the page appear to refresh?

Also, can you share the routes you have set up to a) show the form and b) process the form? 

You're also welcome/encouraged to share the repo URL for this code (if it's on Github; if not, we can continue troubleshooting without).

**Comment by erictracy11492** [comment]
It appears to refresh, but the 'You are here' statement does not show when I added the dump statement and commented out the redirect. My routes are displayed below.
<img width="462" alt="screen shot 2017-11-28 at 8 01 20 pm" src="https://user-images.githubusercontent.com/31494476/33352446-f3023820-d476-11e7-8784-8e1e6fbfd46a.png">

**Comment by erictracy11492** [comment]
Okay got it to work now. The page redirects and the data is entered into phpMyAdmin. I still had a typo in the 'published' validation that was causing the error. Thanks for your help!

**Comment by susanBuck** [comment]
Glad it's sorted out!
