### ISSUE TITLE
Apache Errors when running the Subdomain Example

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-fall2017#18]
I am not able to get the Apache server to run my subdomain example

I keep getting the following Browser error:
```
Not Found

The requested URL / was not found on this server

Apache/2.4.18 (Ubuntu) Server at hello-world-1.oscarrangel.me Port 80
```

The Apache error log that shows a missing language file  error in my hello-world-1 folder but nothing related to the PORTS or any other error.

```
 DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations
[Tue Sep 12 14:36:26 2017] [notice] caught SIGTERM, shutting down
[Tue Sep 12 14:36:28 2017] [notice] Digest: generating secret for digest authentication ...
[Tue Sep 12 14:36:28 2017] [notice] Digest: done
[Tue Sep 12 14:36:29 2017] [notice] FastCGI: process manager initialized (pid 2486)
[Tue Sep 12 14:36:29 2017] [notice] Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations
[Tue Sep 12 15:24:07 2017] [error] [client ::1] File does not exist: /Applications/MAMP/htdocs/hello-world-1/docs-assets, referer: http://localhost/MAMP/?language=English
[Tue Sep 12 15:55:54 2017] [error] cgid daemon process died, restarting
[Tue Sep 12 15:57:32 2017] [notice] caught SIGTERM, shutting down
[Tue Sep 12 15:58:32 2017] [notice] Digest: generating secret for digest authentication ...
[Tue Sep 12 15:58:32 2017] [notice] Digest: done
[Tue Sep 12 15:58:32 2017] [notice] FastCGI: process manager initialized (pid 3660)
[Tue Sep 12 15:58:32 2017] [notice] Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations
[Tue Sep 12 16:21:03 2017] [error] [client ::1] File does not exist: /Applications/MAMP/htdocs/hello-world-1/language
[Tue Sep 12 16:21:19 2017] [error] [client ::1] File does not exist: /Applications/MAMP/bin/mamp/language
[Tue Sep 12 16:24:48 2017] [notice] caught SIGTERM, shutting down
[Tue Sep 12 16:24:54 2017] [notice] Digest: generating secret for digest authentication ...
[Tue Sep 12 16:24:54 2017] [notice] Digest: done
[Tue Sep 12 16:24:54 2017] [notice] FastCGI: process manager initialized (pid 4531)
[Tue Sep 12 16:24:54 2017] [notice] Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations
[Tue Sep 12 16:28:13 2017] [notice] caught SIGTERM, shutting down
[Tue Sep 12 16:34:22 2017] [notice] Digest: generating secret for digest authentication ...
[Tue Sep 12 16:34:22 2017] [notice] Digest: done
[Tue Sep 12 16:34:22 2017] [notice] FastCGI: process manager initialized (pid 4805)
[Tue Sep 12 16:34:22 2017] [notice] Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0 configured -- resuming normal operations_
```

I read in several internet sites that additional files may need to be installed but nothing conclusive.
I used the Terminal Monitor to End several http processes, restarted the server with the same results.

This is the Virtual configuration I used:

```
<VirtualHost *:80>
  ServerName hello-world-1.oscarrangel.me
  DocumentRoot "/var/www/html/hello-world-1”
  <Directory "/var/www/html/hello-world-1”>
    AllowOverride All
  </Directory>
</VirtualHost>
```

**Comment by gabrielsanna** [comment]
Don't forget to close the tags you're opening in your config file:

`<VirtualHost *:80>
ServerName hello-world-1.oscarrangel.me
DocumentRoot "/var/www/html/hello-world-1”
</VirtualHost>
<Directory "/var/www/html/hello-world-1”>
AllowOverride All
</Directory>`

Does that fix your issue?

**Comment by oarangel** [comment]
Virtual config. above is missing the last two lines, here is what I used:

<VirtualHost *:80>
  ServerName hello-world-1.oscarrangel.me
  DocumentRoot "/var/www/html/hello-world-1”
  <Directory "/var/www/html/hello-world-1”>
    AllowOverride All
  </Directory>
</VirtualHost>

**Comment by oarangel** [comment]
For some reason the last two lines are not posted

**Comment by oarangel** [comment]
<img width="909" alt="screen shot 2017-09-12 at 5 09 25 pm" src="https://user-images.githubusercontent.com/31460368/30348447-5c8de644-97dd-11e7-90dd-470dea863d93.png">

**Comment by gabrielsanna** [comment]
Your site is actually serving the files correctly: http://oscarrangel.me/hello-world-1/index.php

But the VirtualHost isn't getting picked up. I don't think that the "language" file issues are causing the problem you're seeing. Did you restart Apache with `sudo apachectl restart`? Does that present any warnings?

**Comment by oarangel** [comment]
I used the sudo apache2 restart command, I am not able to restart the service with the  - sudo apachectl restart   command, it shows the following error:
root@dwa15-fall2017:~# service apachectl restart
Failed to restart apachectl.service: Unit apachectl.service not found.

**Comment by milliezhou** [comment]
Did you clone your git repository to your server? Initially I ran into a similar issue, but cloning my repository to the server fixed the issue.

**Comment by zeroender** [comment]
This could be the apachectl command not being on your system path.  What happens when you try 

service apache2 restart

Also, the log file you attached appears to be from your Mamp instance, rather than the server - there are references to MAMP and localhost.

If service apache2 restart doesn't work, you could grep for apachectl, though I think apache2 is on the PATH by default. What directory are you currently running commands under, and how are you logged into that machine?

To locate apachectl, you could run:

ps -ef | grep apachectl

That should locate the binary, you could add that to your PATH environment variable, or run it in the directory where it resides.

**Comment by oarangel** [comment]
Here is the error log
<img width="1108" alt="screen shot 2017-09-12 at 8 57 39 pm" src="https://user-images.githubusercontent.com/31460368/30354817-19be2f70-97fd-11e7-9b57-bebb2c4e3572.png">

**Comment by gabrielsanna** [comment]
This is interesting. Those "proxyreader" requests near the top look like they're malicious attempts to probe your server:

https://stackoverflow.com/questions/33455700/proxy-radar-found-in-apache-logs-file
https://serverfault.com/questions/753493/apache-access-log-full-of-unauthorized-and-suspicious-requests-how-to-take-acti

Basically, the azenv.php is a piece of software that many websites use that has a known vulnerability, so someone is requesting it from your server on the off chance you're using it. You can try to block those requests if you want, but since you're not using this software, you should be safe.

The SIGTERM messages are from when you're restarting Apache yourself, so those are also nothing to worry about.

**Comment by oarangel** [comment]
Zeroender : Looks like the document root does not exist, see screenshot below
<img width="1099" alt="screen shot 2017-09-12 at 9 25 41 pm" src="https://user-images.githubusercontent.com/31460368/30355402-3593a0d2-9801-11e7-9366-44bd7289ef38.png">

**Comment by gabrielsanna** [comment]
Oh! The weird \xe2, etc. you're seeing at the end of the path are probably mis-copied quotation marks. Apache understands regular " quotation marks, but sometimes when you copy-paste them they are mis-pasted as slanty/curly quotes instead. I would remove all the quotes (you don't need them) from your paths.

```
<VirtualHost *:80>
ServerName hello-world-1.oscarrangel.me
DocumentRoot /var/www/html/hello-world-1
<Directory /var/www/html/hello-world-1>
AllowOverride All
</Directory>
</VirtualHost>
```

**Comment by oarangel** [comment]
Hello Gabriel, quotes were removed, issue resolved.
<img width="404" alt="screen shot 2017-09-12 at 9 42 40 pm" src="https://user-images.githubusercontent.com/31460368/30355759-54bec41c-9803-11e7-977d-9b0b08610f82.png">

**Comment by oarangel** [comment]
No Apache Log Errors displayed
<img width="961" alt="screen shot 2017-09-12 at 9 44 37 pm" src="https://user-images.githubusercontent.com/31460368/30355823-aa55cd1c-9803-11e7-874b-b5af7ff8053e.png">

**Comment by ysrinu** [comment]
Hi oarangel, I understand your issue was resolved on removing quotes. Quotes shouldn't cause an issue.

If you are curious as to get to the bottom of the original root cause, you can debug as below.
Can you edit the file and add quotes manually (instead of copy n paste) and restart apache and see if it works?
If manually typing quotes resolves the issue then copy and paste (as you did the first time) view the file in shell terminal (unix or cmder) using the command:
cat -e <filename>
The '-e' flag will help debug if there's junk/extraneous characters got carried with the paste operation.

Thanks,
-Sri

**Comment by susanBuck** [comment]
@ysrinu The use of curly quotes will cause the issue Oscar was describing, so I think it was the root of his problem.

<img width="759" alt="2017-09-14_1155" src="https://user-images.githubusercontent.com/237711/30440237-f4c0d310-9943-11e7-9329-af95fc592723.png">
