### ISSUE TITLE
Delete in One to Many Relationship

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#194]
@susanBuck You showed us examples of deleting order in many to many relationship (what should be detached before deleting the book). What about one to many relationship, do we need to delete items in a particular order? Do we need to delete an author first before deleting the book, for example?

**Comment by ALiborio** [comment]
I haven't tried this out yet but I imagine it would work very similarly.

If you have a one to many relationship such as the book - author relationship demonstrated in the foobooks examples. If you wanted to delete a book, there is nothing special you need to do. As was shown in the lecture videos/notes only the tags has to be detached before the delete function was invoked.

However, if you wanted to delete an author, since many books may be referencing that author you would have to delete all the books that belong to that author. 

There also looks to be a `dissociate()` method which sets the foreign key to `null`. Of course if the foreign key is not nullable, this will probably cause an error itself if you tried to do it.

**Comment by mfs780** [comment]
I feel @ALiborio is correct. In a One to Many relationship before deleting the One any references to the Many have to be deleted first. In the Author Book example a table would be setup for the Author and one for Books. A join table can then be set up associating one Author ID to one Book ID. Before deleting the Author every association with a Book would have to be deleted first and then the Author itself. This way the Books do not have to be deleted just its association with the Author.

**Comment by dukesnuz** [comment]
Wondering if [this](https://stackoverflow.com/questions/28097859/how-to-delete-related-data-one-to-one-relationships-laravel) would work on a one to many?

**Comment by ysrinu** [comment]
@susanBuck 
I have been relying on database 'cascade' delete functionality all the time.  The Foreign Key relationships are defined at database level and I might as well use their 'cascade on delete' functionality instead of writing delete rules at application programming level.

**Comment by susanBuck** [comment]
👍 to @ALiborio's answer above.

In Foobooks, when a *book* is deleted the corresponding *author* is not deleted because other books may be associated with that author (or may be associated with that author in the future.)

This is technically okay, because it's not leaving any "orphan" foreign key relationships.

Compare this to if we were to delete an *author* without first deleting any *books* associated with it - that would potentially throw an error because you could have `author_id` foreign key fields in the `books` table that were suddenly pointing to rows that don't exist.

The decision to not delete corresponding authors upon book deletion is a design decision, though. It may be appropriate in your app to do the deletion, in which case we can apply what we learned when deleting tags with similar code:

```php
# Get a book to delete
$book = Book::find(1);

# Delete the author associated with this book?
# $book->author->delete(); 
/*
The above would fail because the book as not yet been deleted, 
and it's required that it have an associated author (because `author_id` is not nullable and is a foreign key)

For reference, it would produce this error:
    Integrity constraint violation: 1451 Cannot delete or update a parent row: 
    a foreign key constraint fails (`foobooks`.`books`, CONSTRAINT # `books_author_id_foreign`    
    FOREIGN KEY (`author_id`) REFERENCES `authors` (`id`)) # (SQL: delete from `authors` where `id` = 1)
*/

$book->tags()->detach(); # We know we have to detatch any associated tags before the book is deleted.

$book->delete(); # Delete the book

$book->author()->delete(); # And *now* delete the author
```


@ysrinu It's fine if you want to use MySQL's cascade feature. I elaborated in the videos on why I choose not to, and as a result most students will follow that pattern, but you can defer to personal preference for how you want to handle deletes.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
