### ISSUE TITLE
Creating A Migration Table to Connect Authors and Books Naming Convention

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#195]
#### Question:
When naming the migration table ie(```connect_authors_and_books```) does the order matter? Could we have used ```connect_books_and_authors```  and still ave the same code in the file?

**Comment by nekoCC01** [comment]
As far as I understand it, the naming doesn´t matter in this case, because it is just a custom migration, individually adjusting the structure of existing tables.

The case would be different when creating a new pivot table  `author_book`, that connects many books to many authors. Then the naming is important (-->[ naming conventions](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/33_Relationships_Many_to_Many.md#pivot-tables)) in order to get access to Laravels Eloquent-features (for example accessing all authors of a book via `$book->authors`).

**Comment by dukesnuz** [comment]
@nekoCC01 Thank you.
