### ISSUE TITLE
XAMPP PHP Log Not found

### ISSUE THREAD

**Issue by APuente21** [susanBuck/dwa15-fall2017#2]
The notes indicate that XAMPP users can find all PHP errors under the below directory 
````javascript
C:\xampp\php\logs
````
On my side, there isn't a logs folder under the php directory mentioned above - could the logs be stored somewhere else? Or, is the file missing because there aren't any issues to report?

**Comment by susanBuck** [comment]
Quick answer: You have to create a folder in `c:\xampp\php\logs` and *then* it will start writing to a log file in that location.

---

Background:
Looking in the PHP configuration file I confirmed `C:\xampp\php\logs` was the correct location, but like you, I did not see this location on my machine. While in the config file I also confirmed that error logging was enabled.

I thought maybe it was because no errors had been generated yet, so I forced a PHP error in my test `helloworld.php` file by removing the semi-colon from the end of this line:

```
echo 'Hello World! You are visiting '
```

I refreshed the helloworld page in my browser and confirmed it generated an error, but still there was no `c:\xampp\php\logs`.

Did some Googling and found this post <https://stackoverflow.com/a/43528586> that indicates you have to create that folder. 

So I did that, then refreshed the helloworld page to trigger the error, and sure enough, there was now a `c:\xampp\php\logs\php_error_log` file created.

Really odd behavior. I don't know why XAMPP doesn't just have that directory to start with.

**Comment by susanBuck** [comment]
Quick follow-up to note that I removed reference to PHP error logs in the notes you're referring to. It's weird/confusing you have to create that directory - and PHP errors are shown on the page by default -- so for now, we'll stick with that and keep it simple - focussing on just the Apache/MySQL errors.

**Comment by APuente21** [comment]
Thanks for the feedback!

**Comment by stbenjam** [comment]
In case any Linux users are looking at this, the path is different, the php_error_log goes to the main logs folder so no need to create something under php.  Its in `/opt/lampp/logs`.
