### ISSUE TITLE
Production Pivot Table Seeder Error

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#204]
I created a seeder for pivot table locally and it worked fine. However, when I run it in Production, I am getting an error that the class does not exist. I checked that, the php file and the class is there (see below). Am I running the wrong command or in the wrong order? ( I ran migrations first and then seeders).
![image](https://user-images.githubusercontent.com/31451809/33750307-abcbfe54-db98-11e7-8f8a-0cd4c82dc347.png)

**Comment by gregorycoleman** [comment]
### Error: `Class BooksTableSeeder does not exist`
If you see a message telling you your seeder files does not exist, for example...

```xml
Class BooksTableSeeder does not exist
```

...try running `composer dump-autoload`. This will refresh the class list the the composer autoloader has, which can be a needed step when new classes are added.



From this <https://github.com/susanBuck/dwa15-fall2017/blob/e3a2fa8954d1c31e9003af85f90d62cc78bf5c59/03_Laravel/30_Production_database_setup.md#error-class-bookstableseeder-does-not-exist>

**Comment by ysrinu** [comment]
Many To Many Join table not seeding
https://github.com/susanBuck/dwa15-fall2017/issues/177

running db seed in production, ReflectionException
https://github.com/susanBuck/dwa15-fall2017/issues/150

https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/30_Production_database_setup.md#troubleshooting

**Comment by dianakleban** [comment]
I cannot thank you enough, guys! It worked! Maybe it is a good idea to add it to the notes to many to many relationship lecture since all of us need to create pivot table seeder (new seeder in Production).

**Comment by susanBuck** [comment]
You should get in the habit of always running `composer install` when deploying new code to production ([ref](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/07_Deploy_to_DigitalOcean.md#moving-forward)). 

Not only will this keep your packages updated to match what they are locally, it regenerates your class map (same as running `composer dump-autoload`) so your app on production is aware of any new classes that have been added, including seeders.

This isn't specific to many to many relationships, so I don't feel it's necessary to add to the notes there. I understand a handful of students are bumping into this problem, but it's good to bump into it because you'll learn from it and be refreshed on concepts covered previously.
