### ISSUE TITLE
GET vs POST for the Project

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#25]
@susanBuck I am trying to understand the difference between **GET** and **POST** in forms. You showed us a book example using **GET**, but in the forms examples (checkboxes, radios and etc.) we see **POST.**  I would like to clarify what are we supposed to use in the upcoming Project if, for example, we are just collecting info from the user, something like Bill Splitter wireframe example.

**Comment by susanBuck** [comment]
Hi @dianakleban -

Reviewing [the bullet points of get vs. post](https://github.com/susanBuck/dwa15-fall2017/blob/master/02_PHP/10_Forms.md#get-vs-post) which do you think would be the best method?

In the case of the bill splitter I'd lean towards GET. The data is not sensitive, there's not a lot of it, and you're only retrieving it. On the flip side, maybe you prefer cleaner URLs, in which case you could use POST. 

Now if the bill splitter was taking the data input and saving it to a database, or actually charging users credit cards the amounts, etc. then it would definitely use POST. Since that's not the case, in this instance, it can come down to a matter of preference.

Does that help clarify things?

**Comment by ysrinu** [comment]
@dianakleban , also note that when you use GET, the user will see name-value pairs in the url and can use this url string to manipulate the values (search engine queries for example).
This means you can use your own values which the web form maynot have otherwise allowed (this ofcourse assuming the server side validations are happening to reject the request).

Here's another useful link, scroll down and check the Comparison table
https://www.w3schools.com/tags/ref_httpmethods.asp

**Comment by dianakleban** [comment]
Yes, it does. Thank you.
