### ISSUE TITLE
Clarification re: helpers.php file

### ISSUE THREAD

**Issue by peggyo** [susanBuck/dwa15-fall2017#26]
Do I understand correctly from the lectures that we are permitted to use the helpers.php example that you provide as an include file with our project code? Or, for example, should we be implementing our own `sanitize` function?

**Comment by ysrinu** [comment]
@peggyo , from the lecture video I believe we are allowed to use the helpers.php for our development/debugging purpose and that this code should be removed before pushing to production environment (digital ocean).
I don't think using the provided helpers function would be treated as plagiarism :-)
I will wait for our professor to comment on your question though.

**Comment by mildredfakoya** [comment]
@peggyo , i think it can be used, but in my opinion, trying to create yours if you find the time will make you work better. First of all, understand what needs to be sanitized and why. Then create your own function that will be easier to remember. personally, i find it difficult to work with functions created by others especially when i will be using it frequently.
going further, what we basically need to sanitize is the input coming from a form.
i take advantage of 3 php functions
1. htmlspecialchars() : which will convert special characters to html entities.
2. trim() : to remove  unnecessary characters.(newlines, tabs etc)
3. stripslashes() : to remove backslash
going a little more advanced, you can use the filter_list()  / filter_var() function.
at its basics, throwing this all into a function will look like.
```php
function sanitize($input){
$input = trim($input);
$input = stripslashes($input);
$input = htmlspecialchars($input);
return $input;
}
```
now applying it to form processing will be thus: assuming you have an input field that was named firstName and the http method for the form was POST. the you will get the record and sanitize it thus:
```php
 $name= !empty($_POST['firstName']) ? sanitize($_POST['firstName']) : null;
/*this is simply saying if a user enters a value into the first name input field, pass it through the sanitize function, and if no value is entered, set it to null.*/
```
Hope this helps create yours.

**Comment by susanBuck** [comment]
@peggyo You are welcome/encouraged to use `helpers.php`. 

All the work we're doing now is leading up to using a framework (Laravel) which is going to provide many helpers, just like these. 

@mildredfakoya I agree there's some advantage to constructing your own helpers, but it all depends on where you're at in the process/your understanding of the material. If you feel super comfortable with the material thus far, and that works for you, go for it. On the flip side, using outside/trusted libraries is a common (and learned) practice in software development - and I would not recommend reinventing every wheel. 

I say this just because I don't want any more beginner programmers to feel overwhelmed thinking they have to build their own helpers. It's not an expectation I have at this point.
