### ISSUE TITLE
HTML Forms and value attribute

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#36]
@susanBuck 

# HTML Forms and value attribute

In the notes input forms use the format for value attributes: 
```value="<? if (isset($_GET['keyword'])) echo $_GET['keyword']; ?>"```

In the video you use this format for the value attributes:
```value='<?=$keyword?>```

Does it matter which style is used?

**Comment by susanBuck** [comment]
In the first example you cite, we check if keyword exists before echo'ing it in the display.

In the second example, that checking was done in the logic file:

```php
# Retrieve data from the form
if (isset($_GET['keyword'])) {
    $keyword = $_GET['keyword'];
} else {
    $keyword = '';
}
```

This is an example where it gets fuzzy/open to interpretation whether something should go in your display or logic file. I lean towards the second approach because it makes for cleaner display/HTML code. 

So, no hard "musts" in this case. Use what you prefer/what works best with your code.
