### ISSUE TITLE
Setting up error reporting - permission denied

### ISSUE THREAD

**Issue by erictracy11492** [susanBuck/dwa15-fall2017#38]
<img width="548" alt="screen shot 2017-09-19 at 7 12 48 pm" src="https://user-images.githubusercontent.com/31494476/30619671-9cc17b90-9d6e-11e7-8015-92efb68151b6.png">

When attempting to set up error reporting, I am denied permission. What can I do to fix this? Any help is appreciated!

**Comment by gabrielsanna** [comment]
When you enter a path to a file into the command prompt without a command, and hit enter, the shell attempts to _execute_ the file you specify as a program. This is not a binary or a script that can be executed. You're seeing this error because you don't have "execute" permissions to the file.

To edit the file, you can specify a program to edit it in, such as nano:
`nano /Applications/MAMP/bin/php/php7.1.6/conf/php.ini`

Or, you can open it in your default graphical text editor with the `open` command:
`open /Applications/MAMP/bin/php/php7.1.6/conf/php.ini`

You should be able to do run these commands without getting a permissions error.

**Comment by ysrinu** [comment]
If logged in as 'root' user, you shouldn't have issue editing the file.
If you are trying to run the php.ini file from the command line, that's incorrect.
You just need to set the parameters in the .ini file so as to enable error reporting.

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by erictracy11492** [comment]
Yes, thanks for the help everyone, and thanks for the reminder!
