### ISSUE TITLE
Ports in XAMPP

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#5]
Do we need to check and/or change ports in **XAMPP** if everything is working and running property? (In the notes, you changed them in **MAMP**, but did not mention changing them in **XAMPP**)

**Comment by dmbartles** [comment]
Hey friend, 

If everything is working properly I wouldn't worry! Are yours the same as the default? See below for mine.

![image](https://user-images.githubusercontent.com/31462416/30040978-fe7aecf2-91b3-11e7-940f-ca31d28a73b7.png)

**Comment by zeroender** [comment]
If you are able to get to your helloworld.php file by entering http://localhost/helloworld.php - with no port number in the address - than you definitely have Apache running on 80 (if it was on any other port you would have to enter http://localhost:8888/helloworld.php instead).  You could also run (in a windows cmd):

> netstat -bano

This will tell you what ports are in use by which programs.

HTH!

**Comment by craterd** [comment]
I had Windows 10's default web publishing process running on ports 80 and 443 when I installed XAMPP, and Apache would not start. Had to stop the Windows 10 process so Apache could use the ports. In case it helps anyone else.

**Comment by dlabelle101** [comment]
Apache would not start on my PC due to a port conflict. WIndows 10 PCs have http.sys running by default and it listens on port 80. Solution was to stop http.sys

Error msg
Port 80 in use by "Unable to open process" with PID 4!

Launch services -> World Wide Web publishing service -> stop
Modify the service properties -> set startup to manual

Xampp control panel has to be run as administrator

**Comment by atanasgizdov** [comment]
"I had Windows 10's default web publishing process running on ports 80 and 443 when I installed XAMPP, and Apache would not start. Had to stop the Windows 10 process so Apache could use the ports. In case it helps anyone else."

This is the correct answer, I believe. Ports aren't a huge concern, as long as something else is not active on it

**Comment by susanBuck** [comment]
No need to change ports on XAMPP if everything works.

We only change the ports on MAMP because they default to atypical ports.

**Comment by zeguy** [comment]
@zeroender Tanks for the tip. 

You can run netstat -bano directly in Cmder as long as you're running it as admin (righ-click -> run as admin). I'm sure this is painfully obvious to most bust just wanted to share since a separate Windows shell was opening up and shutting down immediately upon execution on my end before I did that.

**Comment by luke777gu** [comment]
Since it is solved, I will just share an interesting article on ports: https://www.howtogeek.com/233383/why-was-80-chosen-as-the-default-http-port-and-443-as-the-default-https-port/
