### ISSUE TITLE
Change/Add SSH keys allowed by DigitalOcean droplet?

### ISSUE THREAD

**Issue by natethegreat418** [susanBuck/dwa15-fall2017#60]
Hey all,

I tried to find an answer to this on the internet, but didn't have any luck.

I have a work laptop and a home PC.  I've configured both to speak to GitHub (no problems there), but when I set up my DigitalOcean droplet I only set up an SSH key to communicate only from my home PC. I'd love to be able to ssh into the droplet from my laptop as well, but I can't find any settings to add new keys to the droplet.

Thanks for the assist!

-Nate

**Comment by zeroender** [comment]
Hi Nate,

You should be able to add the key you created for GitHub on your work laptop in digitalOcean as well.  I've just checked my digitalOcean account and there doesn't appear to be any limit on how many keys you can have - log in, go to settings, security, and click "Add SSH key" (from the week 1 doc - https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/07_Deploy_to_DigitalOcean.md).  That should be all it takes - hope this helps!

**Comment by gvardany** [comment]
Correct, you should add your laptop's key as well to the droplet following the notes above. There should be no limit on number of keys.

**Comment by susanBuck** [comment]
The above linked notes explain how to add a SSH key to DigitalOcean's setting so that you have the option of adding that SSH key to any **new** droplets that are created.

If you already have a Droplet in existence and wish to add a SSH key from a different computer to it, here's one way to do that:

## Step 1
On your work laptop, generate a new SSH key, if you don't already have one:
```
cd %home%\.ssh
ssh-keygen -t rsa -C "your@email.com"
cat id_rsa.pub
```

Copy the contents of your public key output from the last command.

## Step 2
On your home PC, SSH into your DigitalOcean server and edit your `authorized_keys` file. This is the file that holds public keys that have access to the server.

```
nano ~/.ssh/authorized_keys
```

In this file, you should see your existing key from your home PC. 

Below that, paste in the contents of your `id_rsa.pub` file from your work laptop.

Save your changes, then try to SSH in from your home PC.

**Comment by natethegreat418** [comment]
Thanks all! I should have been more clear: I was looking to add a key to an existing droplet. Thanks for the assist.

**Comment by susanBuck** [comment]
@natethegreat418 Going to close this now, but feel free to post any follow-ups if you run into problems going through the procedures.

**Comment by luke777gu** [comment]
Thanks for this issue, I learnt something new today.
