### ISSUE TITLE
Problems on killing system process using CurrPorts

### ISSUE THREAD

**Issue by z14165899** [susanBuck/dwa15-fall2017#7]
I had a difficulty connecting to Apache server using XAMPP because the system uses local port 80. In order to solve this situation, I downloaded and tried CurrPorts to terminate the system processes, but this does not work. CurrPorts gave me an error message after confirming the Close of Selected TCP Connection, and the message says:

>> "Failed to close one or more TCP connections. Be aware that you must run this tool as admin in order to close TCP connections."

 If I chose Killing Processes of Selected TCP Ports, nothing happened after confirming my operation. 
I also tried to click on Help and Run as Administrator on the top of CurrPorts menu, but the results are the same as described above. If anyone can tell me how to terminated the system processes occupying the port 80, it is very appreciated. 
In order to solve this Apache connection problem without using port 80, I changed Line 58 of httpd.conf Listen 80 to Listen 81 so that the Apache server will connect to port 81 instead of 80. However, in this way, I have to use http://localhost:81 to access the local host, but this does not affect the general use of local host. I am not sure if this is acceptable for the screenshot of the first assignment.
Thank you for any help.

**Comment by atanasgizdov** [comment]
If something is tying up port 80, I would just use 81 or 8888 (default for MAMP). Not sure what the app you have on 80 is but that's why we have more than 1 :) 

If you really want to get port 80 cleared, you can do some diagnostics on what's running and kill it from the Terminal: This is the MAC version but Linux and Windows versions can be found by searching a similar flavor of keywords: https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac 

Take care in doing this if you don't know what it is, because hard stopping processes can lead to some unexpected behavior on your machine. Worst case, you may need to do some file cleanup

**Comment by susanBuck** [comment]
>>  I am not sure if this is acceptable for the screenshot of the first assignment.

Confirming this is fine. It's not required that you use port 80.

I'm puzzled that it wouldn't let you kill the process even when run as admin. If anyone else has insight or the same problem, let us know.

**Comment by rrtx2000** [comment]
I also had a problem getting Apache running in XAMPP. My problem was I already had a different version of Apache installed. I decided to uninstall the other version but it wasn't shown in the add/remove programs area. I found the solution on how to uninstall it on Stackoverflow: https://stackoverflow.com/questions/35112260/apache-2-4-remove-delete-uninstall. Basically, run powershell in administrator mode. Go to the directory your httpd file is in EX: ...apache/bin/httpd.exe and run the command: **.\httpd -k uninstall**

**Comment by davida26** [comment]
Looks like you solved your issue but if you really want to dig into what is on port 80...you can run the below command on your windows shell.

`netstat -ano | findstr :80`

look for the result with _:80_ (ignore the extras, basically matching on any str with 80 in it)

could be something as simple as Skype, I had this happen to me in the past. If you do have Skype open, just quit Skype (make sure to fully close it, always stays open unless you click quit). Run your server and then reopen Skype. It is smart enough to switch ports.

If it is something else running on it, you can get the PID from the above command and then kill it:

`TASKKILL /PID 12345` - where 12345 is your process id.

I see you downloaded CurrPorts as well..so if you prefer to use a graphical user interface:

Use the built-in resource monitor.

`Run > resmon.exe`

Click the Network Tab > Expand the Listening Ports Box. Easy to see here by name. Then you can TASKKILL that process. Just be careful as @atanasgizdov mentioned.

**Comment by kunista** [comment]
I had a similar issue. Couldn't kill a process using CurrPorts, because it was a system process. However, I identified that it was BranchCache service which was listening on port 80. Stopping the service fixed the issue for me. I also had IIS installed which also used port 80. Uninstalled that as well.

**Comment by ysrinu** [comment]
Usually killing a process (to avoid port conflict) is not a good idea because the underlying application can kickoff the same process again (or when system restarted, if on auto-start) and it's port is hijacked meanwhile it will spew error/warnings to the system log.
Either uninstall the offending service or stop the service and disable auto-start (on system start).
Killing a process is very abrupt and 'disgraceful' way of ending it, and should be used as a last resort. Try stopping/disabling instead.
