### ISSUE TITLE
Get vs. Post in Laravel

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#73]
I am just wondering about get vs post in Laravel routing. I noticed that post does not work in the start up Routing (example below). It shows "MethodNotAllowedHttpException", while get works without any issues. Wondering why. I am not sure if it will be covered later on...

```
Route::post('/test', function() {
    return 'My test';
});```

**Comment by susanBuck** [comment]
When you type a URL in your browser to visit it, the method used is GET.

Thus, if you visit `/test` (that's configured via POST) it results in a *MethodNotAllowedHttpException* error, because you're trying to visit a POST route via GET.

In order to visit `/test` via POST it needs to be invoked via a form submission where the `method` is set to POST.

In Week 8, we'll cover working w/ forms in Laravel and we'll be able to use POST routes.

**Comment by dianakleban** [comment]
Make sense. Thanks.

**Comment by ysrinu** [comment]
@dianakleban , @susanBuck 
If you want to test POST from url, you can use the 'Chrome Poster' extension for Chrome
https://chrome.google.com/webstore/detail/chrome-poster/cdjfedloinmbppobahmonnjigpmlajcd?hl=en

This is however to quickly test POST method without actually creating form for your use case. You should eventually have your own form that does POST method.
