### ISSUE TITLE
Warnings during Github deployment

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#74]
I am getting these warnings while adding and committing to github. I am wondering if anyone else is getting them and if I should be concerned about them. The Github repository is getting updated fine, but I don't remember seeing these warnings in the past before we started using Laravel.

![image](https://user-images.githubusercontent.com/31451809/31301241-29439600-aabe-11e7-8a67-d416d93bb665.png)

**Comment by susanBuck** [comment]
Based on the warnings you see, any guesses what might be going on? 

Some clues/suggestions on where to start to understand this:
+ What is `LF` and `CRLF`?
+ Why might you start seeing these warnings on a project involving outside code (Laravel), when you didn't see it in a project involving code written entirely by yourself?
+ <http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/>
+ <https://help.github.com/articles/dealing-with-line-endings/#platform-windows>

Based on the above questions/research, what do you think the solution to this problem is?

**Comment by natethegreat418** [comment]
Thanks @dianakleban for the question and @susanBuck for the guidance. I think I understand the problem, and the answers to your first two questions, but I am not certain about the best strategy to resolve.  I did set a global autocrlf setting but do i need to step through each of my repos and "refresh" them manually?

**Comment by dmbartles** [comment]
I got this as well and was wondering the same!

Here's the artlicle that I used to help explain:
(<link>https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important</link>)

**Comment by dianakleban** [comment]
I understand that different operating systems treat end of lines differently LF vs. CRLF, but I am not sure I understand why it started to appear only when we started to use Laravel. We pushed from Windows to Linux before and did not have any warnings in the past. I also not sure I understand what end of lines we are talking about since we don't have any text files, only php files. We had php files before and the only difference is the use of Laravel framework?

Also, I tried to set it to true and/or false, but I still got those warnings either when I added files or during commits... ```git config --global core.autocrlf```. I think I am still missing something...

**Comment by dianakleban** [comment]
I guess because of the settings of ```text=auto in .gitattributes``` file in github, we are getting these warnings, but I am still not clear how to fix them so we will not get them...

**Comment by susanBuck** [comment]
> I understand that different operating systems treat end of lines differently LF vs. CRLF, but I am not sure I understand why it started to appear only when we started to use Laravel. 

Laravel's code base is authored with LF (Unix), and I suspect that when you save files it's using CRLF (Windows). 

Compare this to code you authored yourself from scratch on your system, which would always use CRLF so there wouldn't be a discrepancy.

Setting the Git config for autocrlf to true *should* suppress the warning:
```bash
git config core.autocrlf true
```

@natethegreat418 were you still getting the warning after trying that?

@dianakleban It sounds like you also set core.autocrlf to true - are you still getting the warning?

@dmbartles Very useful resource!

**Comment by dianakleban** [comment]
This feature is set to true, but I am still getting those warnings, unless I am setting it in the wrong location?
My understanding is that everyone who is trying to deploy from Windows to Git should be seeing the same warnings? Should we just ignore them or it maybe a problem in the future? 

![image](https://user-images.githubusercontent.com/31451809/31364397-13a5df88-ad2a-11e7-8211-ab8caecf71c6.png)

**Comment by ysrinu** [comment]
@dianakleban Is it possible to correct the typo in this post title? (Github)

**Comment by dianakleban** [comment]
@susanBuck I will try the suggestions you mentioned. Does it matter where you set it up? in the root directory or your specific project folder? ```git config core.autocrlf```
Also, I am wondering if other people who have Windows 10 experienced the same warning issue?

**Comment by dukesnuz** [comment]
I am using windows 7 and having same issue.  After setting  ``git config core.autocrlf true``` I am also still have same error message. Trying Susan's option 3 next.

**Comment by drumph33** [comment]
I see the warnings too but it doesn't seem to cause any problems.  I saw the warnings a few times when I wrote my own code too.  I think it happened when a file ended with a blank line but I am not 100% sure on that

**Comment by susanBuck** [comment]
I want to emphasize @drumph33's note that these warnings are not going to cause any problems. In the context we're working in (individuals, not as a group), it's more just a nuisance and you can ignore it while continuing with the rest of your work.

@dianakleban I'd set it globally:
```
git config --global core.autocrlf true
```
And remove any instances of `autocrlf = true` from your project's `.git/config` file, because project level configs (i.e. local configs) will override global configs. We don't want that to happen in this case.

Another [StackOverflow post](https://stackoverflow.com/questions/6500880/git-turn-off-lf-will-be-replaced-by-crlf-warning) suggests you can suppress the warnings with this:
```
git config --global core.safecrlf false
```

Apologies for the "feeling around in the dark" approach to solving this problem - finding this tricky because I haven't managed to replicate the problem on my end.

**Comment by susanBuck** [comment]
Follow-up: I just went through all of the above suggestions with @kunista during office hours and it was the following command that did the trick to suppress the warnings:
```
git config --global core.safecrlf false
```

**Comment by dianakleban** [comment]
Yes, I just tested and works for me. No more warnings. Thank you very much for assisting and finding solution.

**Comment by dukesnuz** [comment]
Working for me also.

**Comment by rrtx2000** [comment]
This also worked for me
`git config --global core.safecrlf false`

**Comment by susanBuck** [comment]
Thanks everyone for confirming - looks like we've got a reliable solution now so I'll close this out.
