### ISSUE TITLE
Route for Page Submitting to Itself

### ISSUE THREAD

**Issue by mconstanti** [susanBuck/dwa15-fall2017#78]
In Part 5 of this week's videos (the trivia example), there are two routes shown

```
Route::get('/', 'TriviaController@index');
Route::get('/check-answer', 'TriviaController@checkAnswer');
```
If our form submits to the same page, would we just include the one Route?

**Comment by ysrinu** [comment]
I think that's correct, since the string uri hasn't changed (if ignoring the GET name value pairs)

**Comment by rrtx2000** [comment]
I think you could also include a route that included the GET value like the book example:
```
Route::get('/book/{title}', function($title) {
    return 'Results for the book: '.$title;
});

Route::get('/book/', function() {
    return 'nothing entered';
});
```

**Comment by mfs780** [comment]
I agree with @rrtx2000. If any params are required for the form submission then a second Route with params can be used.

**Comment by ALiborio** [comment]
I'm not sure it works the same way. When a form is submitted via GET you have the name/value pairs in the query string so your uri would be something like `foobooks.loc/?title=The+Great+Gatsby`, but the title here  would not be used by the `{title}` or `$title` arguments in the route.
You would have to redirect to something like `foobooks.loc/TheGreatGatsby` in order to use the route defined.

**Comment by ysrinu** [comment]
GET uses name value pairs, it's not the same as /book/title
name value pair appear after '?'

**Comment by susanBuck** [comment]
This is a great question because it gets to the essence of routing.

The original question states:

>> If our form submits to the same page, would we just include the one Route?

This language is coming from the perspective of that [traditional web flow approach](https://github.com/susanBuck/dwa15-fall2017/blob/master/03_Laravel/08_Basic_flow.md#basic-flow-1) we saw in P2, where the server was responding to requests for specific pages.

But remember that routing is different - it's not so much about specific pages responding to requests, but instead URLs that can trigger different actions. 

We could lump together our "display the form" and "process the form" into one method and route, but it'll be better to compartmentalize these into two separate methods. As you'll see when we get to form processing, the experience for the user will play out the same.

For now, let's "put a pin" in this question and revisit it next week (8) after we see some examples with form processing.

**Comment by natethegreat418** [comment]
I think that (someone feel free to tell me I am totally wrong :P ), in the case of a form submitting and rendering data to the same URL that two routes, specifically a second route via a POST method might actually make it easier practically and conceptually.  In that paradigm, you ::view the page on initial load and when the POST event occurs you know someone interacted with the form so you can choose to refresh the same URL with a new view/Blade.

**Comment by susanBuck** [comment]
In this week's lecture videos ([Week 8](https://dwa15.dev/week/8)) I show a couple different variations on how you might set up your routes/methods for form processing. These variations are also summarized in the final video (*Part 6: Progressing on P3*).

So now that we have this info, feel free to continue this thread if there's still any confusion or if you have follow-up questions.

Also, I want to amend something I said in my comment above:

>> We could lump together our "display the form" and "process the form" into one method and route, but it'll be better to compartmentalize these into two separate methods. 

Here I said it'd be *better* to use two separate methods, implying it's not okay to use one route/method. This isn't necessarily true - in fact - it's how I build the Foobooks *search* feature. 

It really comes down to personal preference on how you want to design your application flow.

**Comment by susanBuck** [comment]
Closing this thread, but feel free to continue to comment if there are follow-up questions.
