### ISSUE TITLE
Week6 progress log, controller

### ISSUE THREAD

**Issue by ysrinu** [susanBuck/dwa15-fall2017#83]
For foobooks, we had excercise where we created 'WelcomeController' just for the welcome page.
For p3, do we have to do similar? In that case do we have enter justification for 'If you feel your project will require more than this single Controller, explain why'?
In other words does a 'WelcomeController' considered as the '2nd' controller?
I first added this controller and then removed to avoid having to justify!

**Comment by susanBuck** [comment]
I don't see a need for a separate WelcomeController in P3, because it's not like you have a homepage that then links to the page that shows your form (at least, most students won't).

The page that shows your form is itself the "welcome page".

Whether you build this via a controller called WelcomeController, or something else, say BillSplitController, is up to you.
