### ISSUE TITLE
Hidden .env file

### ISSUE THREAD

**Issue by dukesnuz** [susanBuck/dwa15-fall2017#88]
#### running windows 7
When I ssh into my production server -> navigate to foobooks folder -> type ```LS```
Then .env file does not appear, yet if I type nano .env the file opens.
Just wondering why this is.

![foobooks files 101417](https://user-images.githubusercontent.com/3799157/31580445-e87963e6-b11d-11e7-9c3c-12f5a098a939.png)

**Comment by dianakleban** [comment]
I think you need to do ```ls -la``` command in order to see all of the files.

**Comment by dukesnuz** [comment]
@dianakleban  Aahh! Yes. Earlier I had used ```ls la``` and forgot the ```-```. Thank you for catching that for me.

**Comment by ysrinu** [comment]
@dianakleban In unix, files with filenames starting with period (**.**) are **hidden** and will not visible with regular 'ls' command. Use '-a' flag to show hidden files.

https://www.ghacks.net/2009/04/16/linux-tips-view-hidden-files/
https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory

**Comment by susanBuck** [comment]
Tip: On our DigitalOcean servers you can also run `ll` which is an alias for the command `ls -aLF` (https://explainshell.com/explain?cmd=ls+-alF).

This is a common alias a lot of people set, since it's a command we run so frequently.

Other tips:
+ Run `alias` on your DigitalOcean server to see other aliases set.
+ See/edit aliases by editing the file `~/.bashrc`

For more info on creating/editing aliases on your local machine:
+ [Mac terminal : Aliases](https://github.com/susanBuck/dwa15-fall2017/blob/master/00_Command_Line/02_Mac-Terminal.md#aliases)
+ [Windows/Cmder: Aliases](https://github.com/susanBuck/dwa15-fall2017/blob/master/00_Command_Line/03_Windows-Cmder.md#aliases)
