### ISSUE TITLE
Composer.json differences

### ISSUE THREAD

**Issue by dianakleban** [susanBuck/dwa15-fall2017#89]
I just wanted to clarify something. After we installed **debugbar** package locally, when we commit all other changes to Production, the only files which are different are **composer.json** and **composer.lock**.  Do we need to leave them as is (different) or we still need to run ```composer install --no-dev``` command? 

![image](https://user-images.githubusercontent.com/31451809/31625669-7d1df2ba-b26c-11e7-8975-b583a0636828.png)

**Comment by susanBuck** [comment]
Go ahead and add/commit the changes to those files so they're in your version control history.

If you've amended `require-dev`, though, it's not absolutely necessary you run `composer install --no-dev` on production, because it'll only look for changes to your `require` section, to which there are none.  

That being said, there's no harm to running it either, and I think it's good to be in the habit of running `composer install --no-dev` on production after any git pull, just to be sure you do have the latest changes. It's part of the reason this step is included in the [deploy script](https://github.com/susanBuck/dwa15-fall2017/blob/master/01_Servers_and_Git/999_Extras/04_Deployment_script.md) I shared last week.

**Comment by dianakleban** [comment]
I understand. Will this command also overlay .env file in Production or it will only update necessary /vendor info?

**Comment by susanBuck** [comment]
Composer is actually independent from the `.env` files, so it won't have any impact on them.

I could see why you might wonder about this though - because we talked about local/production environments in the context of configs (and thus also `.env` files), and we also see something similar in relation to `require` and `require-dev` in Composer. 

So the concept of "*do one thing locally, do a different thing on production*" has overlap with both environment/configs and how Composer works.

Regarding your last point - The command will update the necessary `/vendor` info.

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by dianakleban** [comment]
Yes, it can be closed. Thank you.
