### ISSUE TITLE
on production git pull origin master

### ISSUE THREAD

**Issue by samanthi22** [susanBuck/dwa15-fall2017#91]
I'm getting the following error on production /var/www/html/p3/app:

error: Your local changes to the following files would be overwritten by merge:
	composer.lock
Please, commit your changes or stash them before you can merge.
Aborting

on local I did "composer update"
and on production I did "composer install --no-dev"

**Comment by ALiborio** [comment]
I believe you need to commit your local changes to `composer.lock` and then pull those changes to your production server. That way when you do `composer install --no-dev` on production it will know which versions to use for the various required packages.

`composer update` will use the latest version of each that meets the "fuzzy" versions defined in `composer.json` while `composer install` will use the versions in `composer.lock`

If you cannot pull the changes to `composer.lock` due to the error mentioned, you can use `git checkout composer.lock` to discard any changes on the production server. Then you should be able to do a `git pull origin master` to sync things back up.

**Comment by gvardany** [comment]
@samanthi22 Indeed you seem not to have committed the `composer.lock` . You can `git stash` it on production, commit and push on local, and then pull again on production site.

**Comment by helhaggaz** [comment]
@samanthi22 you can also discard the changes on production asuming there should not be any change intiated there and every change should come from github.
The command to do that is `git reset --hard`

**Comment by HeinrichTremblay** [comment]
@helhaggaz I would be very careful before using `git reset --hard` tho. It's a powerful command.

**Comment by stbenjam** [comment]
I think `git stash` is much better than a hard reset, since you'll be able to re-apply all those changes you made later if needed.  You may not care about the local changes to composer.lock, but `reset --hard` is a really good way to lose things you don't want to.

**Comment by susanBuck** [comment]
All the above comments provide explanation on how to resolve this problem, I just want to add a note on how I think this problem occurred:

When you attempted to do a `git pull` on production, it aborted because it noticed that `composer.lock` on your production server had changes to the file, and it determined that those changes would conflict with changes you were about to pull.

Typically, the only way `composer.lock` changes is if we run `composer update`. If I had to guess, then, I'd say you ran `composer update` on your production server. Either that, or you manually edited it, but that seems unlikely.

Recall that we want to only run `composer install` on production so it will read configs from `composer.lock` and install/update the packages as necessary.

If you run `composer update` it will read from your `composer.json` file *and* update your `composer.lock` file, creating this potential conflict.

**Comment by susanBuck** [comment]
Bumping this post to see if this issue can be closed or if it's still pending.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
